freebsd_instance:
  image: freebsd-12-0-release-amd64

freebsd_task:
  update_script: pkg update && pkg upgrade -y
  install_script: pkg install -y git pkgconf gmake cmake qt5-qmake qt5-l10n qt5-buildtools qt5-linguisttools qt5-testlib qt5-core qt5-gui qt5-network qt5-sql qt5-svg qt5-widgets qt5-xml boost-libs opus jackit portaudio libsndfile grpc ice avahi-libdns speech-dispatcher python
  fetch_submodules_script: git submodule --quiet update --init --recursive
  build_script:
  - mkdir build && cd build
  - cmake ..
  - gmake -j $(sysctl -n hw.ncpu)
  check_script: gmake check
